### ISSUE TITLE
Squash Commits

### ISSUE THREAD

**Issue by martialblog** [vision-it/puppet-generate-profile#1]
See:
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jacksgt** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by martialblog** [comment]
Done https://github.com/vision-it/puppet-generate-profile/commit/ae43745981d7459782f035f4f1d2dad3a2c02ffc
